root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe ./cmd/server"
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  log = "build-errors.log"
  rerun = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[misc]
  clean_on_exit = true